; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
default_envs = ESP32-debug

[ESP32-base]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_dtr = 0 ; avoid monitor to reset on connect
upload_speed = 921600
lib_ldf_mode = chain+
board_build.filesystem = littlefs
monitor_filters =
    esp32_exception_decoder
    time
build_flags =
    -DPLATFORM_ESP32
    -Iinclude
lib_deps = 
	paulstoffregen/Time @^1.6.1
	adafruit/Adafruit SSD1306 @^2.5.13
	adafruit/Adafruit MCP23017 Arduino Library @^2.3.2
	esp32async/ESPAsyncWebServer @^3.7.7
	arduinogetstarted/ezButton @^1.0.6
	sui77/rc-switch @^2.6.4
    adafruit/RTClib @^2.1.4
	bbx10/DNSServer@^1.1.0
    bblanchon/ArduinoJson@^6.21.4
    squix78/JsonStreamingParser@^1.0.5
    SPIFFSIniFile@^1.0.0

[env:ESP32-debug]
extends = ESP32-base
build_type = debug
build_flags = 
    -DCORE_DEBUG_LEVEL=3    ; verbose logs in dev

[env:ESP32-release]
extends = env:ESP32-base
build_type = release
build_flags =
    -DCORE_DEBUG_LEVEL=0
    
[env:ESP32-test] 
; Board only — compiles on PC and runs on ESP32
extends = env:ESP32-base
build_type = test

[env:Native-test] 
; No board — compiles and runs on PC
platform = native
build_type = test
test_framework = unity
lib_deps = throwtheswitch/Unity @ ^2.6.1
build_flags =
    -DPLATFORM_NATIVE
    -Iinclude
;test_build_src = true
build_src_filter =
    -<*>
    +<core/interfaces/IValve.h>
test_filter = 
    core/*
    embedded/*
test_ignore = embedded/components/*